### ISSUE TITLE
GROOVY_HOME

### ISSUE THREAD

**Issue by sriram04144** [todd-elvers/groovy-to-exe-converter#11]
In case, I need to use only the .jar to .exe feature, I need not have GROOVY_HOME set - it still requires me to have GROOVY_HOME open.

**Comment by todd-elvers** [comment]
Good catch sriram04144!  I'll take a look at that when I get home.  It should absolutely _not_ require the `GROOVY_HOME` parameter be set after using the .JAR to .EXE feature.

**Comment by todd-elvers** [comment]
I'll try to address this issue tomorrow, sorry for the delay.

**Comment by todd-elvers** [comment]
I have found the source of the issue and fixed it https://github.com/todd-elvers/groovy-to-exe-converter/commit/c5397ae73d60bad1c3d02d9f23b0864cdbac94a7

This will be released in 1.3.2 later today.
